repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
    -   id: ruff
        args: [--fix, --cache-dir=.ruff_cache]
        types: [python]
        exclude: ^tests/
        additional_dependencies:
          - types-tqdm
          - instaloader
    -   id: ruff-format
        args: [--cache-dir=.ruff_cache]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        additional_dependencies:
            - types-tqdm
            - instaloader
        args:
            - --cache-dir=.mypy_cache
            - --disallow-untyped-defs
            - --disallow-incomplete-defs
            - --check-untyped-defs
            - --disallow-untyped-decorators
            - --no-implicit-optional
            - --warn-redundant-casts
            - --warn-unused-ignores
            - --warn-return-any
            - --warn-unreachable
            - --strict-optional
            - --ignore-missing-imports

-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.14.0
    hooks:
    -   id: markdownlint-cli2
        files: \.md$

default_language_version:
    python: python3.12

default_stages: [pre-commit, pre-push]

ci:
    autofix_commit_msg: 'ci: auto fixes'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'
    skip: []
    submodules: false