[tool.poetry]
name = "Instalker"
version = "0.1.0"
description = "Download profiles on Instagram"
authors = ["Felippe Andrade <4drade@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
instaloader = "*"
tqdm = "*"

[tool.poetry.group.dev.dependencies]
ruff-lsp = "*"
ruff = "*"
mypy = "*"
types-tqdm = "*"

[tool.mypy]
python_version = "3.13"
strict = true
untyped_calls_exclude = ["instaloader"]
disable_error_code = ["assignment"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["PTH111", "PTH207", "SLF001", "D104", "D203", "D212"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
