[tool.poetry]
name = "Instalker"
version = "0.1.0"
description = "Download profiles on Instagram"
authors = ["Felippe Andrade <4drade@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
instaloader = "^4.13.1"
python-dotenv = "^1.0.1"
tqdm = "^4.66.5"

[tool.poetry.group.dev.dependencies]
ruff-lsp = "^0.0.55"
ruff = "^0.6.3"
mypy = "^1.11.2"
types-tqdm = "^4.66.0.20240417"

[tool.mypy]
python_version = "3.12"
strict = true
untyped_calls_exclude = ["instaloader"]

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["E501", "I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
