[tool.poetry]
name = "Instalker"
version = "0.1.0"
description = "Download profiles on Instagram"
authors = ["Felippe A. <4drade@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
instaloader = "^4.14.1"
tqdm = "^4.67.1"
pillow = "^11.1.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.3"
types-tqdm = "^4.64.7"
types-pillow = "^10.2.0.20240822"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"
select = ["ALL"]
ignore = ["SLF001", "PTH111", "PTH207", "S605"]
per-file-ignores = { "run.py" = ["ERA001"] }

[tool.pyright]
typeCheckingMode = "strict"
useLibraryCodeForTypes = true
reportUnknownMemberType = "none"
reportConstantRedefinition = "none"
