[tool.poetry]
name = "instalker"
version = "0.1.0"
description = ""
authors = ["Felippe Andrade <4drade@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
instaloader = "^4.13.1"
python-dotenv = "^1.0.1"

[tool.poetry.dev-dependencies]
ruff = "^0.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
