name: Code Quality
on: [push, pull_request]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv and project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Run Ruff (Linting)
        uses: astral-sh/ruff-action@v3
        with:
          args: check --fix .
      - name: Run Pyright (Type Checking)
        uses: jakebailey/pyright-action@v1
        with:
          pylance-version: latest-release
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13
