name: Code Quality

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --with dev

      - name: Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: --fix

      - name: Pyright
        uses: jakebailey/pyright-action@v1

      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: "**/*.md"
