name: Code Quality
on: [push, pull_request]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: "poetry"

      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - uses: jakebailey/pyright-action@v1

      - name: Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check --fix .

      - uses: DavidAnson/markdownlint-cli2-action@v13
